---
- name: reload prom config
  ansible.builtin.uri:
    url: http://127.0.0.1:8080/-/reload
    method: POST

- name: restart stack
  service:
    name: docker-compose@monitoring-stack
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
