- name: clone vogon2 repo
  ansible.builtin.git:
    repo: https://github.com/irq0/vogon2.git
    dest: /home/vogon/vogon2
    version: master
    single_branch: yes

- name: virtualenv
  ansible.builtin.pip:
    requirements: /home/vogon/vogon2/requirements.txt
    virtualenv: '{{ vogon_virtualenv }}'
    virtualenv_command: '{{ vogon_python }} -m venv'

- name: scheduler config
  ansible.builtin.template:
    src: sched.json.j2
    dest: /home/vogon/sched.json
  vars:
    json: '{{ vogon_sched | to_nice_json }}'

- name: scheduler directory
  ansible.builtin.file:
    path: /home/vogon/sched
    state: directory
    owner: vogon
    group: vogon
    mode: '0755'

- name: scheduler subdirs
  ansible.builtin.file:
    path: '/home/vogon/sched/{{ item }}'
    state: directory
    owner: vogon
    group: vogon
    mode: '0755'
  loop:
    - todo
    - failed
    - done
    - running

- name: testrun
  ansible.builtin.shell: |
    source /home/vogon/vogon2-py-venv/bin/activate
    /home/vogon/vogon2/vogon2.py --help
