---
- name: install packages (SUSE)
  ansible.builtin.package:
    name:
      - python310
      - python310-setuptools
      - python310-pip
      - sqlite3
      - python3-docker-compose
    state: present
  when: 'ansible_facts["distribution"] == "SLES"'

- name: install packages (Rocky)
  ansible.builtin.package:
    name:
      - epel-release
      - python3
      - python3-setuptools
      - python3-pip
      - sqlite
    state: present
  when: 'ansible_facts["distribution"] == "Rocky"'

- name: Install packages
  ansible.builtin.package:
    name:
      - htop
      - smartmontools
      - zsh
      - git-core
      - tmux
      - lshw
      - fio
      - sudo
      - iotop
      - sysstat
      - dstat
      - ccache
      - binutils
      - attr
      - parted
      - perf
      - bcc-tools
      - noto-sans-fonts
      - noto-coloremoji-fonts
      - gdouros-symbola-fonts
    state: present

- name: enable systemd persistent journal
  file:
    path: /var/log/journal
    mode: "0755"
    state: directory


- name: docker
  when: container_runtime == 'docker'
  block:
    - name: Install packages
      ansible.builtin.package:
        name:
          - docker
    - name: docker daemon config
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: enable docker service
      ansible.builtin.systemd:
        state: started
        name: docker
        enabled: true
        masked: false

- name: podman
  when: container_runtime == 'podman'
  block:
    - name: Install packages
      ansible.builtin.package:
        name:
          - podman

    - name: enable podman service
      ansible.builtin.systemd:
        state: started
        name: podman
        enabled: true
        masked: false

    - name: podman sock dir
      ansible.builtin.file:
        path: '/run/podman'
        state: directory
        owner: root
        group: docker
        mode: '0755'

    - name: podman sock
      ansible.builtin.file:
        path: '/run/podman/podman.sock'
        state: touch
        owner: root
        group: docker
        mode: '0660'
