---
- name: Install packages
  community.general.zypper:
    name:
      - htop
      - smartmontools
      - zsh
      - git-core
      - screen
      - tmux
      - lshw
      - sqlite3
      - python310
      - python310-setuptools
      - python310-pip
      - fio
      - sudo
      - iotop
      - sysstat
      - dstat
      - docker
    state: present

- name: enable systemd persistent journal
  file:
    path: /var/log/journal
    mode: "0755"
    state: directory

- name: docker daemon config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: enable docker service
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true
    masked: false
