---
- name: vogon group
  ansible.builtin.group:
    name: vogon
    state: present

- name: vogon user
  ansible.builtin.user:
    name: vogon
    uid: 1337
    groups:
      - vogon
      - docker
    shell: /bin/bash
    password: "!"

- name: sudoers
  ansible.builtin.copy:
    content: "vogon ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/vogon
    mode: "0400"
