- name: make vogon user own vogon disks
  ansible.builtin.file:
    path: '{{ item }}'
    state: file
    owner: vogon
    group: vogon
    mode: '0660'
    follow: true
  loop: '{{ vogon_disks }}'

- name: make vogon mountpoint
  ansible.builtin.file:
    path: '/home/vogon/mnt'
    state: directory
    owner: vogon
    group: vogon
    mode: '0775'
