{
 "title": "S3GW",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "operation", "query": { "query": "rgw_op_svc_time_bucket" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "What's happening?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "targets": [
      { "expr": "rgw_qactive", "legendFormat": "Active" },
      { "expr": "rgw_qlen", "legendFormat": "Total Queue Length" }
     ]
    },
    {
     "title": "All Ops Average Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rgw_op_svc_time_bucket{op=~\"$operation\"})",
       "legendFormat": "median"
      },
      {
       "expr": "histogram_quantile(0.9, rgw_op_svc_time_bucket{op=~\"$operation\"})",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, rgw_op_svc_time_bucket{op=~\"$operation\"})",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, rgw_op_svc_time_bucket{op=~\"$operation\"})",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Important Ops [Rate]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(rgw_op_svc_time_count{op=~\"get_obj|put_obj|create_bucket|delete_obj\"}[$__rate_interval])",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "RGW Throughput",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(rgw_put_b_total[$__rate_interval])",
       "legendFormat": "PUT"
      },
      {
       "expr": "rate(rgw_get_b_total[$__rate_interval])",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "All Ops [Rate]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(rgw_op_svc_time_count[$__rate_interval]) > 0",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Failed Requests [Rate]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(rgw_failed_req_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=\"nvme0n1\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{device=\"nvme0n1\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "node_filefd_allocated", "legendFormat": "Open files" }
     ]
    },
    {
     "title": "Disk Average Wait Time",
     "type": "timeseries",
     "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{device=\"nvme0n1\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{device=\"nvme0n1\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read wait time avg"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{device=\"nvme0n1\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{device=\"nvme0n1\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write wait time avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Focus: Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$operation Service Time",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(rate(rgw_op_svc_time_bucket{op=\"$operation\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "$operation histogram",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 6, "x": 17, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rgw_op_svc_time_bucket{op=\"$operation\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3GW Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Retried [rate]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(rgw_sfs_retry_total_total[$__rate_interval])",
       "legendFormat": "transactions ran with retry"
      },
      {
       "expr": "rate(rgw_sfs_retry_retried_count_total[$__rate_interval])",
       "legendFormat": "retried transactions"
      },
      {
       "expr": "rate(rgw_sfs_retry_failed_count_total[$__rate_interval])",
       "legendFormat": "retried until failure"
      }
     ]
    },
    {
     "title": "SQLite Connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
     "targets": [
      { "expr": "sfs_sqlite_connection_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "SFS SQLite DB/WAL Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "sfs_sqlite_db_bytes", "legendFormat": "DB" },
      { "expr": "sfs_sqlite_db_wal_bytes", "legendFormat": "WAL" }
     ]
    },
    {
     "title": "SFS Filesystem",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "sfs_filesystem_total_bytes", "legendFormat": "Total" },
      { "expr": "sfs_filesystem_avail_bytes", "legendFormat": "Available" }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Runs",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
     "targets": [
      { "expr": "rgw_sfs_gc_process_exit", "legendFormat": "GC Process Exit" },
      { "expr": "rgw_sfs_gc_count_total", "legendFormat": "Total GC Runs" }
     ]
    },
    {
     "title": "GC Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "rgw_sfs_gc_process_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rgw_sfs_gc_pending_objects_data_elapsed",
       "legendFormat": "Pending Objects Data"
      },
      {
       "expr": "rgw_sfs_gc_deleted_buckets_elapsed",
       "legendFormat": "Deleted Buckets"
      },
      {
       "expr": "rgw_sfs_gc_deleted_objects_elapsed",
       "legendFormat": "Deleted Objects"
      },
      {
       "expr": "rgw_sfs_gc_pending_multiparts_data_elapsed",
       "legendFormat": "Pending Multiparts Data"
      }
     ]
    }
   ]
  },
  {
   "title": "SQLite Query Profiling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLite Profiling: Query Time",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "sum(rate(rgw_prom_hist_sfs_sqlite_profile_bucket[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}