---
- name: Server base
  hosts: all
  roles:
    - user-accounts
    - packages

- name: Partitions
  hosts: equinix
  roles:
    - storage-partitions

- name: Monitoring Stack
  hosts: ares
  roles:
    - monitoring-stack

- name: Storage
  hosts: all
  roles:
    - storage

- name: Install vogon2
  hosts: all
  become: yes
  become_user: vogon
  roles:
    - vogon2
